# Фикстуры для тестов бота.
# Структура соответствует реальной схеме БД.
# Используются как замена ответов бэка (GET /api/books, /api/authors и т.д.)

authors = [
    {"id": 13,  "name": "Аркадий и Борис Стругацкие"},
    {"id": 21,  "name": "Виктор Пелевин"},
    {"id": 28,  "name": "Габриэль Гарсиа Маркес"},
    {"id": 50,  "name": "Дуглас Адамс"},
    {"id": 57,  "name": "Евгения Гинзбург"},
    {"id": 79,  "name": "Марина и Сергей Дяченко"},
    {"id": 86,  "name": "Михаил Булгаков"},
    {"id": 118, "name": "Сергей Довлатов"},
    {"id": 140, "name": "Фёдор Достоевский"},
    {"id": 144, "name": "Фредрик Бакман"},
    {"id": 146, "name": "Фрэнк Герберт"},
    {"id": 150, "name": "Харуки Мураками"},
]

members = [
    {"id": 1,  "telegram_username": "alyona_reads",   "telegram_id": 111001, "telegram_fullname": "Алёна"},
    {"id": 2,  "telegram_username": "sergey_b",       "telegram_id": 111002, "telegram_fullname": "Серёжа"},
    {"id": 3,  "telegram_username": "marina_k",       "telegram_id": 111003, "telegram_fullname": "Марина"},
    {"id": 4,  "telegram_username": "bookworm_pavel", "telegram_id": 111004, "telegram_fullname": "Павел"},
    {"id": 5,  "telegram_username": "katya_book",     "telegram_id": 111005, "telegram_fullname": "Катя"},
    {"id": 6,  "telegram_username": "dima_reads",     "telegram_id": 111006, "telegram_fullname": "Дима"},
    {"id": 7,  "telegram_username": "olga_pages",     "telegram_id": 111007, "telegram_fullname": "Оля"},
    {"id": 8,  "telegram_username": "anton_lit",      "telegram_id": 111008, "telegram_fullname": "Антон"},
    {"id": 9,  "telegram_username": "natasha_wolf",   "telegram_id": 111009, "telegram_fullname": "Наташа"},
    {"id": 10, "telegram_username": "vas_petrov",     "telegram_id": 111010, "telegram_fullname": "Вася"},
]

books = [
    {
        "id": 1,
        "title": "Крутой маршрут",
        "author_id": 57,
        "country": None,
        "added_by_member_id": 1,
        "added_at": "2022-03-19",
        "status": "read",
        "elected_poll_id": None,
        "elected_at": "2022-03-19",
        "annotation": None,
        "discussion_url": None,
    },
    {
        "id": 2,
        "title": "Vita Nostra",
        "author_id": 79,
        "country": None,
        "added_by_member_id": 2,
        "added_at": "2022-04-09",
        "status": "read",
        "elected_poll_id": None,
        "elected_at": "2022-04-10",
        "annotation": None,
        "discussion_url": None,
    },
    {
        "id": 3,
        "title": "Чемодан",
        "author_id": 118,
        "country": None,
        "added_by_member_id": 3,
        "added_at": "2022-04-10",
        "status": "read",
        "elected_poll_id": None,
        "elected_at": "2022-06-27",
        "annotation": None,
        "discussion_url": None,
    },
    {
        "id": 4,
        "title": "Пикник на обочине",
        "author_id": 13,
        "country": None,
        "added_by_member_id": 4,
        "added_at": "2025-09-01",
        "status": "to_read",
        "elected_poll_id": None,
        "elected_at": None,
        "annotation": None,
        "discussion_url": None,
    },
    {
        "id": 5,
        "title": "Автостопом по галактике",
        "author_id": 50,
        "country": None,
        "added_by_member_id": 5,
        "added_at": "2025-10-15",
        "status": "to_read",
        "elected_poll_id": None,
        "elected_at": None,
        "annotation": None,
        "discussion_url": None,
    },
    {
        "id": 6,
        "title": "Дюна",
        "author_id": 146,
        "country": None,
        "added_by_member_id": 4,
        "added_at": "2026-02-28",
        "status": "to_read",
        "elected_poll_id": None,
        "elected_at": None,
        "annotation": None,
        "discussion_url": None,
    },
    {
        "id": 7,
        "title": "Мастер и Маргарита",
        "author_id": 86,
        "country": None,
        "added_by_member_id": 1,
        "added_at": "2026-01-10",
        "status": "to_read",
        "elected_poll_id": None,
        "elected_at": None,
        "annotation": None,
        "discussion_url": None,
    },
    {
        "id": 8,
        "title": "Generation П",
        "author_id": 21,
        "country": None,
        "added_by_member_id": 3,
        "added_at": "2026-03-05",
        "status": "to_read",
        "elected_poll_id": None,
        "elected_at": None,
        "annotation": None,
        "discussion_url": None,
    },
    {
        "id": 9,
        "title": "Сто лет одиночества",
        "author_id": 28,
        "country": None,
        "added_by_member_id": 2,
        "added_at": "2025-11-20",
        "status": "removed",
        "elected_poll_id": None,
        "elected_at": None,
        "annotation": None,
        "discussion_url": None,
    },
    {
        "id": 10,
        "title": "Норвежский лес",
        "author_id": 150,
        "country": None,
        "added_by_member_id": 6,
        "added_at": "2026-01-05",
        "status": "to_read",
        "elected_poll_id": None,
        "elected_at": None,
        "annotation": None,
        "discussion_url": None,
    },
    {
        "id": 11,
        "title": "Идиот",
        "author_id": 140,
        "country": None,
        "added_by_member_id": 7,
        "added_at": "2026-01-18",
        "status": "to_read",
        "elected_poll_id": None,
        "elected_at": None,
        "annotation": None,
        "discussion_url": None,
    },
    {
        "id": 12,
        "title": "Бесконечная шутка",
        "author_id": 144,
        "country": None,
        "added_by_member_id": 8,
        "added_at": "2026-02-03",
        "status": "to_read",
        "elected_poll_id": None,
        "elected_at": None,
        "annotation": None,
        "discussion_url": None,
    },
    {
        "id": 13,
        "title": "Трудно быть богом",
        "author_id": 13,
        "country": None,
        "added_by_member_id": 9,
        "added_at": "2026-02-14",
        "status": "to_read",
        "elected_poll_id": None,
        "elected_at": None,
        "annotation": None,
        "discussion_url": None,
    },
    {
        "id": 14,
        "title": "Собачье сердце",
        "author_id": 86,
        "country": None,
        "added_by_member_id": 10,
        "added_at": "2026-03-01",
        "status": "to_read",
        "elected_poll_id": None,
        "elected_at": None,
        "annotation": None,
        "discussion_url": None,
    },
    {
        "id": 15,
        "title": "Преступление и наказание",
        "author_id": 140,
        "country": None,
        "added_by_member_id": 6,
        "added_at": "2026-03-10",
        "status": "to_read",
        "elected_poll_id": None,
        "elected_at": None,
        "annotation": None,
        "discussion_url": None,
    },
    {
        "id": 16,
        "title": "Зона",
        "author_id": 118,
        "country": None,
        "added_by_member_id": 3,
        "added_at": "2022-05-15",
        "status": "read",
        "elected_poll_id": None,
        "elected_at": "2022-05-20",
        "annotation": None,
        "discussion_url": None,
    },
    {
        "id": 17,
        "title": "Мессия Дюны",
        "author_id": 146,
        "country": None,
        "added_by_member_id": 4,
        "added_at": "2026-03-20",
        "status": "to_read",
        "elected_poll_id": None,
        "elected_at": None,
        "annotation": None,
        "discussion_url": None,
    },
    {
        "id": 18,
        "title": "Ресторан на краю вселенной",
        "author_id": 50,
        "country": None,
        "added_by_member_id": 9,
        "added_at": "2026-03-25",
        "status": "to_read",
        "elected_poll_id": None,
        "elected_at": None,
        "annotation": None,
        "discussion_url": None,
    },
    {
        "id": 19,
        "title": "Осень патриарха",
        "author_id": 28,
        "country": None,
        "added_by_member_id": 10,
        "added_at": "2025-12-01",
        "status": "removed",
        "elected_poll_id": None,
        "elected_at": None,
        "annotation": None,
        "discussion_url": None,
    },
]

polls = [
    {
        "id": 1,
        "parent_poll_id": None,
        "stage": 1,
        "date": "2026-03-01",
        "winner_book_id": None,
        "total_voters": 4,
    },
    {
        "id": 2,
        "parent_poll_id": 1,
        "stage": 2,
        "date": "2026-03-08",
        "winner_book_id": 6,
        "total_voters": 5,
    },
]

poll_votes = [
    {"id": 1, "poll_id": 1, "book_id": 4, "votes_count": 3},
    {"id": 2, "poll_id": 1, "book_id": 5, "votes_count": 2},
    {"id": 3, "poll_id": 1, "book_id": 6, "votes_count": 4},
    {"id": 4, "poll_id": 2, "book_id": 5, "votes_count": 2},
    {"id": 5, "poll_id": 2, "book_id": 6, "votes_count": 3},
]

award_votes = [
    {"id": 1, "year": 2022, "book_id": 1, "liked_votes": 4, "disliked_votes": 1, "round2_votes": None, "is_winner": False},
    {"id": 2, "year": 2022, "book_id": 2, "liked_votes": 5, "disliked_votes": 0, "round2_votes": 4,    "is_winner": True},
    {"id": 3, "year": 2022, "book_id": 3, "liked_votes": 3, "disliked_votes": 2, "round2_votes": None, "is_winner": False},
]


# --- Вспомогательные функции для тестов ---

def get_author_by_id(author_id: int) -> dict | None:
    return next((a for a in authors if a["id"] == author_id), None)

def get_member_by_telegram_id(telegram_id: int) -> dict | None:
    return next((m for m in members if m["telegram_id"] == telegram_id), None)

def get_books_by_status(status: str) -> list:
    return [b for b in books if b["status"] == status]

def get_book_by_title(title: str) -> dict | None:
    return next((b for b in books if b["title"].lower() == title.lower()), None)

def author_name_exists(name: str) -> bool:
    return any(a["name"].lower() == name.lower() for a in authors)
